name: openclaw-reseller
region: sfo
services:
  - name: web
    github:
      repo: alvelda/openclaw-reseller
      branch: main
      deploy_on_push: true
    build_command: npm run build
    run_command: npm start
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: STRIPE_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        scope: RUN_AND_BUILD_TIME
        type: GENERAL
      - key: NEXT_PUBLIC_APP_URL
        scope: RUN_AND_BUILD_TIME
        type: GENERAL
